### ISSUE TITLE
License of the ontology?

### ISSUE THREAD

**Issue by k00ni** [digitalconstruction/Units#1]
There is no information about the license to be found. I checked the Turtle file https://digitalconstruction.github.io/Units/v/0.5/units.ttl as well as https://digitalconstruction.github.io/Units/v/0.5/. Many other Digital Construction ontologies use CC-BY 4.0, may I assume this one does too?

**Comment by seppotorma** [comment]
Hi,

The license is CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/).

It is missing by mistake.

Best regards,
Seppo

pe 15. maalisk. 2024 klo 16.51 Konrad Abicht ***@***.***)
kirjoitti:

**Comment by k00ni** [comment]
Thank you.
